language: sh
env:
  global:
  - REPO_DIR=.
  - BUILD_COMMIT=$TRAVIS_COMMIT
  - PLAT=x86_64
install:
- git clone https://github.com/matthew-brett/multibuild && cd multibuild && git checkout
  254ad28 && cd ..
- ". multibuild/common_utils.sh"
- ". multibuild/travis_steps.sh"
- before_install
- build_wheel $REPO_DIR $PLAT
script:
- install_run $PLAT
matrix:
  include:
  - os: windows
    env:
    # - MB_PYTHON_VERSION=3.5
    #- MB_PYTHON_VERSION=3.6
    - MB_PYTHON_VERSION=3.7
    install:
    - choco install --yes python3 --version $MB_PYTHON_VERSION 
    - choco install --yes make
    - export PYROOT=/c/Python${MB_PYTHON_VRESION//./}
    - export PATH=$PYROOT:$PYROOT/Scripts:$PATH
    - pip install cmake
    - "./installzlib.bat"
    - make
    - cp atari_py/ale_interface/build/Debug/ale_c.dll atari_py/ale_interface/ale_c.dll
    script:
    - pip install wheel && pip wheel . -w wheelhouse --no-deps -vvv
    - ls wheelhouse/atari_py* 
    - rm -rf atari_py*
    - pip install $(ls wheelhouse/atari_py*)
    - pip install pytest
    - pytest --pyargs atari_py.tests
    
deploy:
  provider: s3
  access_key_id: AKIAIR7X3BP26ZWUNFPA
  skip_cleanup: true
  secret_access_key:
    secure: wUNE0AxIZ3rQVO6pUXQyfOVI4UN/4bgTb+y8566pFYQ68mzZEW3XNl96n8HtkHGYuJGnNGWGbGKcp2a1MCoiyePR+NnmoUxCledUffU+s88Sxg9Qj7DW8JOLImocNXG+8y2OeC+QjmrkB109inM0c2T+ESeLZi9yALaLSxVEKToXB1EBDtOohjelNcA8xoP9yb4H6yoT01XLNkno2o9fmKc+ZXtLi9xZVpMX1aH0Hs2pchm0WmE7d93XVD0K9ZM/2q1yT8ojJngKAbpJeJQSSSJStNpFBIp7hc+2slFP9/QOCPJQZQuIjJkHj2iXEMgIrerbFgl/n5konQiZFHwDZbmubQR8cfVOmr/+By8n9h13rzL7OpqCx84f4QuaRifRY6vMnu0nqbo7M7vkW0fEzcMOEpn1fcL0ulOOFc9Oedyvn08flK2M3DX10rglncK+MkGdWjH23K/1PLNOCIdNO8kWO+yvuCbdx1oJzMcpr5w52Sh+pWt4xXk1TQvXtzPVxLxf+mGumHvU1wSFW2IbBcLIv3C/BeqeNbyRNIrXT2rfaOzDj8LEXOq3IIdfgKmHx2a4Iz3V3S2a5vJiXeBtr9G4LtH/k9eRRyr6CKN+HqSZSRnwL0W8i3u7QvcP6wSF91lJCpAJpsuu5faE3RKfW/hUd/gsmo1f1tcJZEaCkzo=
  bucket: games-wheels
  local-dir: wheelhouse
  upload-dir: atari-py
  acl: public_read
  on:
    repo: openai/atari-py
    branch: windows_build
