language: sh
env:
  global:
    - REPO_DIR=.
    - BUILD_COMMIT=$TRAVIS_COMMIT
    - PLAT=x86_64

install: 
  - git clone https://github.com/matthew-brett/multibuild && cd multibuild && git checkout 254ad28 && cd ..
  - . multibuild/common_utils.sh
  - . multibuild/travis_steps.sh
  - before_install 
  - build_wheel $REPO_DIR $PLAT
script: 
  - install_run $PLAT

after_success:
  - ./deploy.sh

    
matrix:
  include:

#     - os: linux
#       env:
#         - MB_PYTHON_VERSION=3.5
#     
#     - os: linux
#       env:
#         - MB_PYTHON_VERSION=3.6
#  
#     - os: linux
#       env:
#         - MB_PYTHON_VERSION=3.7
# 
# 
#     - os: osx
#       osx_image: xcode8.3
#       env:
#         - MB_PYTHON_VERSION=3.5
#         - DEPLOY_SDIST=true
#  
#     - os: osx
#       osx_image: xcode8.3
#       env:
#         - MB_PYTHON_VERSION=3.6
#  
#     - os: osx
#       osx_image: xcode8.3
#       env:
#         - MB_PYTHON_VERSION=3.7
 
    - os: windows
      env:
        - MB_PYTHON_VERSION=3.6
 
      install:
        - choco install --yes python3
        - choco install --yes make
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - echo $PATH
        - which python
        - which pip
        - pip install virtualenv

      script:
        - pip install cmake
        - ./installzlib1.bat
        # - make build -C atari_py/ale_interface 
        # - cp atari_py/ale_interface/build/Debug/ale_c.dll atari_py/ale_interface/build/ale_c.dll
        - pip install .
        - pip install wheel && pip wheel . -w wheelhouse
        - ls -lht wheelhouse
        - rm -rf atari_py
        - pip install pytest
        - pytest --pyargs atari_py

